services:
  api_gateway:
    image: api_gateway
    volumes:
      - ./api_gateway/logs:/logs
      - ./api_gateway/config:/config
    user: root
    build:
      context: ./api_gateway
      dockerfile: ./Dockerfile
    ports:
      - 9000:9000
